# Generated by Django 3.1.4 on 2021-01-10 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_delete_follow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_subscriptions'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptions',
            unique_together={('user', 'author')},
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
            ],
            managers=[
                ('purchase', django.db.models.manager.Manager()),
            ],
        ),
    ]
