# Generated by Django 3.1.4 on 2021-01-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0022_auto_20210115_2306'),
        ('api', '0005_auto_20210114_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='recipe',
        ),
        migrations.AddField(
            model_name='purchase',
            name='recipes',
            field=models.ManyToManyField(related_name='purchases', to='recipes.Recipe'),
        ),
    ]
