# Generated by Django 3.1.4 on 2020-12-05 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20201205_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientforrecipe',
            old_name='unit',
            new_name='amount',
        ),
    ]
