# Generated by Django 3.1.4 on 2020-12-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_auto_20201222_0207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='breakfast',
            field=models.BooleanField(default=False, verbose_name='Затрак'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='dinner',
            field=models.BooleanField(default=False, verbose_name='Ужин'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='lunch',
            field=models.BooleanField(default=False, verbose_name='Обед'),
        ),
    ]
