# Generated by Django 3.1.4 on 2020-12-21 23:54

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('recipes', '0016_auto_20201222_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='breakfast',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='dinner',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='lunch',
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
