# Generated by Django 3.1.4 on 2020-12-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0017_auto_20201222_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='tags',
        ),
        migrations.AddField(
            model_name='recipe',
            name='breakfast',
            field=models.BooleanField(default=False, verbose_name='Завтрак'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='dinner',
            field=models.BooleanField(default=False, verbose_name='Ужин'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='lunch',
            field=models.BooleanField(default=False, verbose_name='Обед'),
        ),
    ]
