# Generated by Django 3.1.4 on 2021-01-04 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0020_delete_favoriterecipes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
