# Generated by Django 3.1.4 on 2021-01-15 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0021_delete_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-pub_date']},
        ),
    ]
