# Generated by Django 3.1.4 on 2021-01-28 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0025_auto_20210128_2041'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipeTagMapping',
        ),
    ]
